### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### ISSUE THREAD

**Issue by Minami-su** [mobiusml/hqq#33]
Traceback (most recent call last):
  File "/home/luhao/orpo/2bit-qz.py", line 1, in <module>
    from hqq.core.quantize import *
  File "/root/anaconda3/envs/train/lib/python3.9/site-packages/hqq/core/quantize.py", line 8, in <module>
    from .utils import is_divisible
  File "/root/anaconda3/envs/train/lib/python3.9/site-packages/hqq/core/utils.py", line 18, in <module>
    tensor: torch.Tensor, num_rows: int, dtype: torch.dtype | None = None
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by Minami-su** [comment]
Ok,I need python>=3.10.
